// src/pages/Contact.tsx
import { useState } from 'react';
import { Send, CheckCircle, Github, Linkedin, Mail, MapPin } from 'lucide-react';
import { motion } from 'framer-motion';
import { supabase } from '../../utils/supabase/client';
import Lanyard from '../components/reactbits/Lanyard';
import { useLanguage } from '../context/LanguageContext';

export default function Contact() {
    const [formData, setFormData] = useState({ name: '', email: '', message: '' });
    const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
    const { t } = useLanguage();

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setStatus('loading');

        try {
            const { error } = await supabase
                .from('messages')
                .insert([formData]);

            if (error) throw error;

            setStatus('success');
            setFormData({ name: '', email: '', message: '' });
            setTimeout(() => setStatus('idle'), 3000);
        } catch (error) {
            console.error('Error sending message:', error);
            setStatus('error');
            setTimeout(() => setStatus('idle'), 3000);
        }
    };

    return (
        <div className="pt-32 pb-20 px-6 min-h-screen bg-white">
            <div className="max-w-7xl mx-auto grid lg:grid-cols-[1fr,1fr,420px] gap-12">

                {/* Contact Info */}
                <div>
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6 }}
                    >
                        <span className="text-sm font-bold text-gray-400 tracking-widest uppercase mb-4 block">{t.contact.label}</span>
                        <h1 className="text-5xl md:text-7xl font-bold mb-8 tracking-tighter font-display">{t.contact.title}</h1>
                        <p className="text-xl text-gray-500 max-w-lg mb-12">
                            {t.contact.subtitle}
                        </p>
                    </motion.div>

                    <div className="space-y-6">
                        <motion.a
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.5, delay: 0.2 }}
                            href="mailto:cahyadiprasetyo@example.com"
                            className="flex items-center gap-4 p-6 bg-gray-50 rounded-2xl border border-gray-100 hover:bg-gray-100 transition-colors"
                        >
                            <Mail className="text-gray-900" size={24} />
                            <div>
                                <h3 className="font-bold text-gray-900">{t.contact.email}</h3>
                                <p className="text-gray-500">cahyadiprasetyo@example.com</p>
                            </div>
                        </motion.a>

                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.5, delay: 0.3 }}
                            className="flex gap-4"
                        >
                            <a href="https://github.com/Cahyadi-Prasetyo" target="_blank" rel="noopener noreferrer" className="flex-1 flex items-center justify-center gap-3 p-6 bg-gray-50 rounded-2xl border border-gray-100 hover:bg-gray-100 transition-colors">
                                <Github size={24} />
                                <span className="font-bold">GitHub</span>
                            </a>
                            <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" className="flex-1 flex items-center justify-center gap-3 p-6 bg-gray-50 rounded-2xl border border-gray-100 hover:bg-gray-100 transition-colors">
                                <Linkedin size={24} />
                                <span className="font-bold">LinkedIn</span>
                            </a>
                        </motion.div>

                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.5, delay: 0.4 }}
                            className="flex items-center gap-4 p-6 rounded-2xl border border-gray-100"
                        >
                            <MapPin className="text-gray-400" size={24} />
                            <p className="text-gray-500 font-medium">Bintan, Kepulauan Riau, Indonesia</p>
                        </motion.div>
                    </div>
                </div>

                {/* Form */}
                <div>
                    <motion.form
                        initial={{ opacity: 0, y: 30 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6, delay: 0.3 }}
                        onSubmit={handleSubmit}
                        className="bg-gray-50 p-8 md:p-12 rounded-3xl border border-gray-200"
                    >
                        <div className="space-y-6">
                            <div>
                                <label htmlFor="name" className="block text-sm font-bold text-gray-900 mb-2">{t.contact.form.name}</label>
                                <input
                                    type="text"
                                    id="name"
                                    required
                                    value={formData.name}
                                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                    className="w-full px-4 py-4 bg-white border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-black/5 focus:border-black transition-all"
                                    placeholder={t.contact.form.namePlaceholder}
                                />
                            </div>
                            <div>
                                <label htmlFor="email" className="block text-sm font-bold text-gray-900 mb-2">{t.contact.form.email}</label>
                                <input
                                    type="email"
                                    id="email"
                                    required
                                    value={formData.email}
                                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                                    className="w-full px-4 py-4 bg-white border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-black/5 focus:border-black transition-all"
                                    placeholder={t.contact.form.emailPlaceholder}
                                />
                            </div>
                            <div>
                                <label htmlFor="message" className="block text-sm font-bold text-gray-900 mb-2">{t.contact.form.message}</label>
                                <textarea
                                    id="message"
                                    required
                                    rows={6}
                                    value={formData.message}
                                    onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                                    className="w-full px-4 py-4 bg-white border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-black/5 focus:border-black transition-all resize-none"
                                    placeholder={t.contact.form.messagePlaceholder}
                                />
                            </div>

                            <button
                                type="submit"
                                disabled={status === 'loading'}
                                className="w-full py-4 bg-black text-white rounded-xl font-bold text-lg hover:bg-gray-800 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
                            >
                                {status === 'loading' ? t.contact.form.sending : status === 'success' ? (
                                    <>
                                        <CheckCircle size={20} /> {t.contact.form.sent}
                                    </>
                                ) : (
                                    <>
                                        <Send size={20} /> {t.contact.form.send}
                                    </>
                                )}
                            </button>

                            {status === 'error' && (
                                <p className="text-red-500 text-sm text-center">{t.contact.form.error}</p>
                            )}
                        </div>
                    </motion.form>
                </div>

                {/* Lanyard Sidebar - NOW WITH LARGER DISPLAY */}
                <div className="hidden lg:block">
                    <div className="sticky top-24">
                        <motion.div
                            initial={{ opacity: 0, scale: 0.9 }}
                            animate={{ opacity: 1, scale: 1 }}
                            transition={{ duration: 0.6, delay: 0.5 }}
                            className="rounded-2xl overflow-hidden bg-gray-50/30"
                        >
                            <Lanyard position={[0, 0, 15]} gravity={[0, -40, 0]} />
                        </motion.div>
                    </div>
                </div>

            </div>
        </div>
    );
}

// src/routes/contact/+page.svelte
<script lang="ts">
    import { getTranslations } from "$lib/i18n/index.svelte";

    const t = $derived(getTranslations());

    let formData = $state({
        name: "",
        email: "",
        subject: "",
        message: "",
    });

    let sending = $state(false);
    let sent = $state(false);

    function handleSubmit(e: Event) {
        e.preventDefault();
        sending = true;

        const mailto = `mailto:${t.contact.email}?subject=${encodeURIComponent(formData.subject)}&body=${encodeURIComponent(`Name: ${formData.name}\nEmail: ${formData.email}\n\n${formData.message}`)}`;
        window.open(mailto, "_blank");

        setTimeout(() => {
            sending = false;
            sent = true;
            formData = { name: "", email: "", subject: "", message: "" };
            setTimeout(() => { sent = false; }, 3000);
        }, 500);
    }
</script>

<svelte:head>
    <title>{t.contact.title} • Cahyadi Prasetyo</title>
</svelte:head>

<div class="page">
    <div class="container">
        <section class="header reveal">
            <h1 class="page-title">{t.contact.title}</h1>
            <p class="page-desc">{t.contact.desc}</p>
        </section>

        <div class="contact-layout">
            <form class="contact-form reveal" onsubmit={handleSubmit}>
                <div class="form-row">
                    <div class="form-group">
                        <label for="name">{t.contact.nameLabel}</label>
                        <input type="text" id="name" bind:value={formData.name} placeholder={t.contact.namePlaceholder} required />
                    </div>
                    <div class="form-group">
                        <label for="email">{t.contact.emailLabel}</label>
                        <input type="email" id="email" bind:value={formData.email} placeholder={t.contact.emailPlaceholder} required />
                    </div>
                </div>

                <div class="form-group">
                    <label for="subject">{t.contact.subjectLabel}</label>
                    <input type="text" id="subject" bind:value={formData.subject} placeholder={t.contact.subjectPlaceholder} required />
                </div>

                <div class="form-group">
                    <label for="message">{t.contact.messageLabel}</label>
                    <textarea id="message" bind:value={formData.message} placeholder={t.contact.messagePlaceholder} rows="5" required></textarea>
                </div>

                <button type="submit" class="btn btn-primary submit-btn" disabled={sending}>
                    {#if sending}
                        Sending...
                    {:else if sent}
                        ✓ Sent!
                    {:else}
                        {t.contact.send} →
                    {/if}
                </button>
            </form>

            <div class="contact-aside reveal">
                <div class="aside-block">
                    <p class="aside-label">{t.contact.orEmail}</p>
                    <a href="mailto:{t.contact.email}" class="aside-email">{t.contact.email}</a>
                </div>
                <div class="aside-block">
                    <p class="aside-label">Social</p>
                    <div class="aside-links">
                        <a href="https://github.com/Cahyadi-Prasetyo" target="_blank" rel="noopener">GitHub</a>
                        <a href="https://linkedin.com/" target="_blank" rel="noopener">LinkedIn</a>
                        <a href="https://instagram.com/" target="_blank" rel="noopener">Instagram</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .page {
        padding-top: calc(var(--nav-height) + var(--space-3xl));
        padding-bottom: var(--space-4xl);
        min-height: 100vh;
    }

    .page-title {
        font-size: var(--text-4xl);
        font-weight: 800;
        letter-spacing: -0.03em;
        margin-bottom: var(--space-sm);
    }

    .page-desc {
        font-size: var(--text-base);
        color: var(--text-secondary);
        margin-bottom: var(--space-2xl);
    }

    .contact-layout {
        display: grid;
        grid-template-columns: 1fr 280px;
        gap: var(--space-4xl);
        align-items: start;
    }

    .contact-form {
        display: flex;
        flex-direction: column;
        gap: var(--space-lg);
    }

    .form-row {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: var(--space-lg);
    }

    .form-group {
        display: flex;
        flex-direction: column;
        gap: 6px;
    }

    .form-group label {
        font-size: var(--text-sm);
        font-weight: 500;
        color: var(--text);
    }

    .form-group input,
    .form-group textarea {
        font-family: 'Inter', sans-serif;
        font-size: var(--text-base);
        padding: 12px 16px;
        border: 1px solid var(--border);
        border-radius: var(--radius-md);
        background: var(--white);
        color: var(--text);
        transition: border-color var(--transition-fast);
        outline: none;
        resize: vertical;
    }

    .form-group input::placeholder,
    .form-group textarea::placeholder {
        color: var(--text-muted);
    }

    .form-group input:focus,
    .form-group textarea:focus {
        border-color: var(--text);
    }

    .submit-btn {
        width: 100%;
        justify-content: center;
    }

    .contact-aside {
        display: flex;
        flex-direction: column;
        gap: var(--space-xl);
    }

    .aside-label {
        font-size: var(--text-xs);
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        color: var(--text-muted);
        margin-bottom: var(--space-sm);
    }

    .aside-email {
        font-size: var(--text-sm);
        font-weight: 600;
        color: var(--text);
        word-break: break-all;
    }

    .aside-email:hover {
        opacity: 0.7;
    }

    .aside-links {
        display: flex;
        flex-direction: column;
        gap: var(--space-sm);
    }

    .aside-links a {
        font-size: var(--text-sm);
        font-weight: 500;
        color: var(--text-secondary);
        transition: color var(--transition-fast);
    }

    .aside-links a:hover {
        color: var(--text);
    }

    @media (max-width: 768px) {
        .contact-layout {
            grid-template-columns: 1fr;
            gap: var(--space-2xl);
        }

        .form-row {
            grid-template-columns: 1fr;
        }
    }
</style>
