// app/projects/page.tsx
'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { motion, AnimatePresence } from 'framer-motion'
import { createClient } from '@/utils/supabase/client'
import { ArrowUpRight } from 'lucide-react'

type Project = {
    id: string
    title: string
    slug: string
    description: string
    image: string | null
    tags: string[]
}

export default function ProjectsPage() {
    const [projects, setProjects] = useState<Project[]>([])
    const [filter, setFilter] = useState<'all' | 'web' | 'mobile'>('all')
    const [loading, setLoading] = useState(true)

    useEffect(() => {
        fetchProjects()
    }, [])

    async function fetchProjects() {
        const supabase = createClient()
        const { data } = await supabase
            .from('projects')
            .select('*')
            .order('created_at', { ascending: false })

        if (data) setProjects(data)
        setLoading(false)
    }

    const filteredProjects = projects.filter(project => {
        if (filter === 'all') return true
        return project.tags.some(tag => tag.toLowerCase().includes(filter))
    })

    return (
        <main className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-gray-100">
            <div className="max-w-7xl mx-auto px-6 lg:px-12 pt-32 pb-20">
                {/* Header */}
                <div className="mb-24">
                    <span className="text-sm font-medium text-gray-400 tracking-widest mb-6 block">
                        PORTFOLIO
                    </span>
                    <h1 className="text-7xl md:text-8xl lg:text-9xl font-bold text-gray-900 tracking-tight mb-8">
                        Selected
                        <span className="block bg-gradient-to-r from-gray-900 via-gray-700 to-gray-500 bg-clip-text text-transparent">
                            Work
                        </span>
                    </h1>
                    <p className="text-2xl text-gray-600 max-w-3xl font-light">
                        A collection of projects that showcase my expertise in building modern,
                        scalable web applications.
                    </p>
                </div>

                {/* Filter Tabs - Premium Style */}
                <div className="flex gap-4 mb-20">
                    {[
                        { key: 'all', label: 'All Projects' },
                        { key: 'web', label: 'Web' },
                        { key: 'mobile', label: 'Mobile' }
                    ].map((tab) => (
                        <button
                            key={tab.key}
                            onClick={() => setFilter(tab.key as typeof filter)}
                            className={`px-8 py-4 rounded-2xl text-lg font-medium transition-all duration-300 ${filter === tab.key
                                    ? 'bg-gray-900 text-white shadow-lg scale-105'
                                    : 'bg-white text-gray-600 hover:bg-gray-100 border-2 border-gray-200'
                                }`}
                        >
                            {tab.label}
                        </button>
                    ))}
                </div>

                {/* Projects Grid - Premium */}
                <div className="grid lg:grid-cols-2 gap-8">
                    <AnimatePresence mode="wait">
                        {filteredProjects.map((project, index) => (
                            <motion.div
                                key={project.id}
                                initial={{ opacity: 0, y: 40 }}
                                animate={{ opacity: 1, y: 0 }}
                                exit={{ opacity: 0, y: -40 }}
                                transition={{ delay: index * 0.1, duration: 0.5 }}
                            >
                                <Link
                                    href={`/projects/${project.slug}`}
                                    className="group relative block overflow-hidden rounded-3xl bg-gray-900 aspect-[4/3] hover:scale-[1.02] transition-transform duration-700"
                                >
                                    {/* Background Image with Parallax */}
                                    {project.image && (
                                        <div className="absolute inset-0 overflow-hidden">
                                            <img
                                                src={project.image}
                                                alt={project.title}
                                                className="w-full h-full object-cover opacity-30 group-hover:opacity-50 group-hover:scale-110 transition-all duration-1000"
                                            />
                                        </div>
                                    )}

                                    {/* Gradient Overlay - More Sophisticated */}
                                    <div className="absolute inset-0 bg-gradient-to-br from-gray-900/90 via-gray-900/70 to-gray-900/90 group-hover:from-gray-900/80 group-hover:via-gray-900/60 group-hover:to-gray-900/80 transition-all duration-700" />

                                    {/* Content */}
                                    <div className="relative h-full p-10 lg:p-12 flex flex-col justify-between">
                                        {/* Number - Larger & Bolder */}
                                        <div className="text-white/20 text-8xl lg:text-9xl font-bold font-mono leading-none">
                                            {String(index + 1).padStart(2, '0')}
                                        </div>

                                        {/* Title & CTA */}
                                        <div className="space-y-8">
                                            <div>
                                                <h2 className="text-5xl lg:text-6xl font-bold text-white mb-6 group-hover:translate-x-3 transition-transform duration-500 leading-tight">
                                                    {project.title}
                                                </h2>
                                                <p className="text-gray-300 text-xl font-light leading-relaxed">
                                                    {project.description}
                                                </p>
                                            </div>

                                            {/* Tags */}
                                            {project.tags && project.tags.length > 0 && (
                                                <div className="flex flex-wrap gap-3">
                                                    {project.tags.slice(0, 3).map((tag) => (
                                                        <span
                                                            key={tag}
                                                            className="px-4 py-2 bg-white/10 backdrop-blur-sm text-white text-sm rounded-full border border-white/20"
                                                        >
                                                            {tag}
                                                        </span>
                                                    ))}
                                                </div>
                                            )}

                                            {/* CTA Button */}
                                            <div className="inline-flex items-center gap-3 px-8 py-4 bg-white text-gray-900 rounded-2xl font-semibold text-lg group-hover:bg-gray-100 group-hover:scale-105 transition-all duration-300 shadow-xl">
                                                View Project
                                                <ArrowUpRight className="group-hover:translate-x-1 group-hover:-translate-y-1 transition-transform" size={20} />
                                            </div>
                                        </div>
                                    </div>

                                    {/* Shine Effect on Hover */}
                                    <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-700">
                                        <div className="absolute top-0 -left-full h-full w-1/2 bg-gradient-to-r from-transparent via-white/10 to-transparent transform group-hover:translate-x-[300%] transition-transform duration-1000" />
                                    </div>
                                </Link>
                            </motion.div>
                        ))}
                    </AnimatePresence>
                </div>

                {/* Empty State - Premium */}
                {filteredProjects.length === 0 && !loading && (
                    <div className="text-center py-32">
                        <div className="text-gray-300 text-8xl mb-8">∅</div>
                        <p className="text-2xl text-gray-400 font-light">
                            No projects found in this category.
                        </p>
                    </div>
                )}
            </div>
        </main>
    )
}

// src/routes/projects/+page.svelte
<script lang="ts">
    import { getTranslations, getCurrentLang } from "$lib/i18n/index.svelte";
    import { getProjectsByCategory, type Project } from "$lib/data/projects";
    import FooterCTA from "$lib/components/FooterCTA.svelte";

    const t = $derived(getTranslations());
    const currentLang = $derived(getCurrentLang());

    let activeFilter = $state<"all" | "web" | "mobile" | "ai">("all");
    let filteredProjects = $derived(getProjectsByCategory(activeFilter));

    function setFilter(filter: "all" | "web" | "mobile" | "ai") {
        activeFilter = filter;
    }
</script>

<svelte:head>
    <title>{t.projects.title} • Cahyadi Prasetyo</title>
</svelte:head>

<div class="page">
    <div class="container">
        <section class="header reveal">
            <h1 class="page-title">{t.projects.title}</h1>
            <p class="page-desc">{t.projects.desc}</p>
        </section>

        <div class="filters reveal">
            <button class="filter" class:active={activeFilter === "all"} onclick={() => setFilter("all")}>
                {t.projects.filterAll}
            </button>
            <button class="filter" class:active={activeFilter === "web"} onclick={() => setFilter("web")}>
                {t.projects.filterWeb}
            </button>
            <button class="filter" class:active={activeFilter === "mobile"} onclick={() => setFilter("mobile")}>
                {t.projects.filterMobile}
            </button>
            <button class="filter" class:active={activeFilter === "ai"} onclick={() => setFilter("ai")}>
                {t.projects.filterAI}
            </button>
        </div>

        <div class="projects-grid">
            {#each filteredProjects as project (project.slug)}
                <a href="/projects/{project.slug}" class="project-card fade-in">
                    <div class="project-image">
                        <img src={project.imageUrl} alt={project.title} loading="lazy" />
                        <div class="project-overlay">
                            <span class="project-view">View Project →</span>
                        </div>
                    </div>
                    <div class="project-body">
                        <div class="project-meta-row">
                            <span class="project-cat">{project.category}</span>
                        </div>
                        <h3 class="project-title">{project.title}</h3>
                        <p class="project-desc">
                            {currentLang === "id" ? project.shortDesc.id : project.shortDesc.en}
                        </p>
                        <div class="project-tags">
                            {#each project.tech.slice(0, 4) as tech}
                                <span class="tag">{tech}</span>
                            {/each}
                        </div>
                    </div>
                </a>
            {/each}
        </div>

        {#if filteredProjects.length === 0}
            <div class="empty-state">
                <p>Belum ada proyek di kategori ini.</p>
            </div>
        {/if}
    </div>

    <FooterCTA />
</div>

<style>
    .page {
        padding-top: calc(var(--nav-height) + var(--space-3xl));
        padding-bottom: var(--space-2xl);
        min-height: 100vh;
    }

    .page-title {
        font-size: var(--text-4xl);
        font-weight: 800;
        letter-spacing: -0.03em;
        margin-bottom: var(--space-sm);
    }

    .page-desc {
        font-size: var(--text-base);
        color: var(--text-secondary);
        margin-bottom: var(--space-2xl);
    }

    .filters {
        display: flex;
        gap: var(--space-sm);
        margin-bottom: var(--space-2xl);
    }

    .filter {
        padding: 8px 18px;
        font-size: var(--text-sm);
        font-weight: 500;
        color: var(--text-muted);
        border: 1px solid var(--border);
        border-radius: var(--radius-full);
        background: transparent;
        transition: all var(--transition-fast);
    }

    .filter:hover {
        color: var(--text);
        border-color: var(--text);
    }

    .filter.active {
        background: var(--text);
        color: var(--white);
        border-color: var(--text);
    }

    /* Projects Grid */
    .projects-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: var(--space-xl);
    }

    /* Fade-in animation for filtered items — NOT using .reveal to avoid IntersectionObserver dependency */
    .fade-in {
        animation: cardFadeIn 0.35s ease both;
    }

    @keyframes cardFadeIn {
        from {
            opacity: 0;
            transform: translateY(8px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    .project-card {
        text-decoration: none;
        border: 1px solid var(--border);
        border-radius: var(--radius-lg);
        overflow: hidden;
        transition: all var(--transition-base);
        background: var(--white);
    }

    .project-card:hover {
        border-color: var(--text-muted);
        transform: translateY(-2px);
        box-shadow: 0 8px 24px rgba(0, 0, 0, 0.06);
    }

    .project-image {
        position: relative;
        width: 100%;
        aspect-ratio: 16 / 10;
        overflow: hidden;
        background: var(--bg-alt);
    }

    .project-image img {
        width: 100%;
        height: 100%;
        object-fit: cover;
        transition: transform var(--transition-base);
    }

    .project-card:hover .project-image img {
        transform: scale(1.03);
    }

    .project-overlay {
        position: absolute;
        inset: 0;
        background: rgba(0, 0, 0, 0.5);
        display: flex;
        align-items: center;
        justify-content: center;
        opacity: 0;
        transition: opacity var(--transition-base);
    }

    .project-card:hover .project-overlay {
        opacity: 1;
    }

    .project-view {
        font-size: var(--text-sm);
        font-weight: 600;
        color: var(--white);
        padding: 10px 20px;
        border: 1px solid rgba(255, 255, 255, 0.6);
        border-radius: var(--radius-full);
    }

    .project-body {
        padding: var(--space-lg);
    }

    .project-meta-row {
        margin-bottom: var(--space-sm);
    }

    .project-cat {
        font-size: var(--text-xs);
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        color: var(--text-muted);
    }

    .project-title {
        font-size: var(--text-lg);
        font-weight: 700;
        color: var(--text);
        margin-bottom: var(--space-xs);
    }

    .project-desc {
        font-size: var(--text-sm);
        color: var(--text-secondary);
        line-height: 1.6;
        margin-bottom: var(--space-md);
        display: -webkit-box;
        -webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
        overflow: hidden;
    }

    .project-tags {
        display: flex;
        flex-wrap: wrap;
        gap: 4px;
    }

    .empty-state {
        text-align: center;
        padding: var(--space-4xl) 0;
        color: var(--text-muted);
    }

    @media (max-width: 768px) {
        .projects-grid {
            grid-template-columns: 1fr;
        }

        .filters {
            flex-wrap: wrap;
        }
    }
</style>
