// src/pages/Projects.tsx
import { useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowUpRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useLanguage } from '../context/LanguageContext';
import Magnet from '../components/reactbits/Magnet';
import CountUp from '../components/reactbits/CountUp';

const categories = [
    { id: 'all', labelId: 'Semua', labelEn: 'All' },
    { id: 'web', labelId: 'Website', labelEn: 'Website' },
    { id: 'api', labelId: 'API', labelEn: 'API' },
    { id: 'mobile', labelId: 'Mobile', labelEn: 'Mobile' },
];

// Tilt Card Component
function TiltCard({ children, className = '' }: { children: React.ReactNode; className?: string }) {
    const [rotateX, setRotateX] = useState(0);
    const [rotateY, setRotateY] = useState(0);

    const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
        const card = e.currentTarget;
        const rect = card.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;
        const centerX = rect.width / 2;
        const centerY = rect.height / 2;

        const rotateXValue = ((y - centerY) / centerY) * -10;
        const rotateYValue = ((x - centerX) / centerX) * 10;

        setRotateX(rotateXValue);
        setRotateY(rotateYValue);
    };

    const handleMouseLeave = () => {
        setRotateX(0);
        setRotateY(0);
    };

    return (
        <div
            className={`transition-transform duration-300 ease-out ${className}`}
            style={{
                transform: `perspective(1000px) rotateX(${rotateX}deg) rotateY(${rotateY}deg)`,
                transformStyle: 'preserve-3d'
            }}
            onMouseMove={handleMouseMove}
            onMouseLeave={handleMouseLeave}
        >
            {children}
        </div>
    );
}

// Hover Count Card Component - triggers CountUp on hover
function HoverCountCard({ index, language, projectSlug }: { index: number; language: string; projectSlug: string }) {
    const [isHovered, setIsHovered] = useState(false);

    const targetNumber = index + 1;
    const formattedNumber = targetNumber.toString().padStart(3, '0');

    return (
        <div
            className="flex justify-between items-center py-4 px-6 border-t border-black"
            onMouseEnter={() => setIsHovered(true)}
            onMouseLeave={() => setIsHovered(false)}
        >
            <div className="text-sm font-medium font-mono flex items-center">
                DEV.<span className="text-emerald-500 min-w-[3ch]">
                    {isHovered ? (
                        <CountUp
                            from={0}
                            to={targetNumber}
                            duration={0.5}
                            startWhen={true}
                            className="inline-block"
                        />
                    ) : (
                        formattedNumber
                    )}
                </span>
            </div>
            <Magnet padding={30} magnetStrength={3}>
                <Link
                    to={`/projects/${projectSlug}`}
                    className="inline-flex items-center gap-2 px-4 py-2 bg-black text-white rounded-full text-sm font-medium uppercase tracking-wider hover:bg-gray-800 transition-colors"
                >
                    {language === 'ID' ? 'LIHAT' : 'VIEW'} <ArrowUpRight size={16} />
                </Link>
            </Magnet>
        </div>
    );
}

export default function Projects() {
    const { t, language } = useLanguage();
    const [activeFilter, setActiveFilter] = useState('all');

    // Filter projects based on active category
    const filteredProjects = activeFilter === 'all'
        ? t.projectsList
        : t.projectsList.filter((p: any) => p.category === activeFilter);

    return (
        <div className="pt-24 md:pt-32 pb-20 min-h-screen bg-white">
            {/* Title */}
            <div className="px-6">
                <div className="max-w-7xl mx-auto">
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6 }}
                        className="text-center"
                    >
                        <h1 className="text-5xl md:text-7xl font-bold mt-10 font-display">{t.projectsPage.title}</h1>
                    </motion.div>
                </div>
            </div>

            {/* Filter Section with 2 Lines - Full Width */}
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.2 }}
                className="w-full border-t border-b border-black py-6 mb-16 mt-10"
            >
                <div className="max-w-7xl mx-auto px-6">
                    <div className="flex flex-wrap justify-center gap-3 md:gap-6">
                        {categories.map((cat) => (
                            <Magnet key={cat.id} padding={30} magnetStrength={3}>
                                <button
                                    onClick={() => setActiveFilter(cat.id)}
                                    className={`px-6 py-2.5 rounded-full text-sm md:text-base font-medium uppercase tracking-wider transition-all duration-300 ${activeFilter === cat.id
                                        ? 'bg-black text-white'
                                        : 'bg-gray-100 text-gray-500 hover:bg-gray-200 hover:text-gray-700'
                                        }`}
                                >
                                    {language === 'ID' ? cat.labelId : cat.labelEn}
                                </button>
                            </Magnet>
                        ))}
                    </div>
                </div>
            </motion.div>

            {/* Projects Grid - 2 Columns */}
            <div className="px-6">
                <div className="max-w-7xl mx-auto">
                    <div className="grid md:grid-cols-2 gap-8">
                        {filteredProjects.map((project, index) => (
                            <motion.div
                                key={project.id}
                                initial={{ opacity: 0, y: 50 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ duration: 0.6, delay: index * 0.1 }}
                                className="border border-black"
                            >
                                {/* Project Title */}
                                <div className="py-4 px-6 border-b border-black text-center">
                                    <h2 className="text-xl md:text-2xl font-bold font-display tracking-tight">
                                        {project.title}
                                    </h2>
                                </div>

                                {/* 3D Tilt Image */}
                                <div className="relative p-6 bg-gray-50">
                                    <TiltCard className="cursor-pointer">
                                        <div className="relative overflow-hidden rounded-lg shadow-2xl">
                                            <img
                                                src={project.image}
                                                alt={project.title}
                                                className="w-full aspect-[16/10] object-cover hover:scale-105 transition-transform duration-500"
                                            />
                                            {/* Shine effect on hover */}
                                            <div className="absolute inset-0 bg-gradient-to-tr from-transparent via-white/20 to-transparent opacity-0 hover:opacity-100 transition-opacity duration-500" />
                                        </div>
                                    </TiltCard>
                                </div>

                                {/* Bottom Info: DEV.001 and LIHAT button */}
                                <HoverCountCard index={index} language={language} projectSlug={project.slug} />
                            </motion.div>
                        ))}
                    </div>
                </div>
            </div>

            {/* Empty State */}
            {filteredProjects.length === 0 && (
                <div className="px-6">
                    <div className="max-w-7xl mx-auto text-center py-20">
                        <p className="text-gray-400 text-xl">
                            {language === 'ID' ? 'Tidak ada project di kategori ini' : 'No projects in this category'}
                        </p>
                    </div>
                </div>
            )}
        </div>
    );
}

// src/routes/projects/+page.svelte
<script lang="ts">
    import { getTranslations, getCurrentLang } from "$lib/i18n/index.svelte";
    import { getProjectsByCategory, type Project } from "$lib/data/projects";
    import FooterCTA from "$lib/components/FooterCTA.svelte";

    const t = $derived(getTranslations());
    const currentLang = $derived(getCurrentLang());

    let activeFilter = $state<"all" | "web" | "mobile" | "ai">("all");
    let filteredProjects = $derived(getProjectsByCategory(activeFilter));

    function setFilter(filter: "all" | "web" | "mobile" | "ai") {
        activeFilter = filter;
    }
</script>

<svelte:head>
    <title>{t.projects.title} • Cahyadi Prasetyo</title>
</svelte:head>

<div class="page">
    <div class="container">
        <section class="header reveal">
            <h1 class="page-title">{t.projects.title}</h1>
            <p class="page-desc">{t.projects.desc}</p>
        </section>

        <div class="filters reveal">
            <button class="filter" class:active={activeFilter === "all"} onclick={() => setFilter("all")}>
                {t.projects.filterAll}
            </button>
            <button class="filter" class:active={activeFilter === "web"} onclick={() => setFilter("web")}>
                {t.projects.filterWeb}
            </button>
            <button class="filter" class:active={activeFilter === "mobile"} onclick={() => setFilter("mobile")}>
                {t.projects.filterMobile}
            </button>
            <button class="filter" class:active={activeFilter === "ai"} onclick={() => setFilter("ai")}>
                {t.projects.filterAI}
            </button>
        </div>

        <div class="projects-grid">
            {#each filteredProjects as project (project.slug)}
                <a href="/projects/{project.slug}" class="project-card fade-in">
                    <div class="project-image">
                        <img src={project.imageUrl} alt={project.title} loading="lazy" />
                        <div class="project-overlay">
                            <span class="project-view">View Project →</span>
                        </div>
                    </div>
                    <div class="project-body">
                        <div class="project-meta-row">
                            <span class="project-cat">{project.category}</span>
                        </div>
                        <h3 class="project-title">{project.title}</h3>
                        <p class="project-desc">
                            {currentLang === "id" ? project.shortDesc.id : project.shortDesc.en}
                        </p>
                        <div class="project-tags">
                            {#each project.tech.slice(0, 4) as tech}
                                <span class="tag">{tech}</span>
                            {/each}
                        </div>
                    </div>
                </a>
            {/each}
        </div>

        {#if filteredProjects.length === 0}
            <div class="empty-state">
                <p>Belum ada proyek di kategori ini.</p>
            </div>
        {/if}
    </div>

    <FooterCTA />
</div>

<style>
    .page {
        padding-top: calc(var(--nav-height) + var(--space-3xl));
        padding-bottom: var(--space-2xl);
        min-height: 100vh;
    }

    .page-title {
        font-size: var(--text-4xl);
        font-weight: 800;
        letter-spacing: -0.03em;
        margin-bottom: var(--space-sm);
    }

    .page-desc {
        font-size: var(--text-base);
        color: var(--text-secondary);
        margin-bottom: var(--space-2xl);
    }

    .filters {
        display: flex;
        gap: var(--space-sm);
        margin-bottom: var(--space-2xl);
    }

    .filter {
        padding: 8px 18px;
        font-size: var(--text-sm);
        font-weight: 500;
        color: var(--text-muted);
        border: 1px solid var(--border);
        border-radius: var(--radius-full);
        background: transparent;
        transition: all var(--transition-fast);
    }

    .filter:hover {
        color: var(--text);
        border-color: var(--text);
    }

    .filter.active {
        background: var(--text);
        color: var(--white);
        border-color: var(--text);
    }

    /* Projects Grid */
    .projects-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: var(--space-xl);
    }

    /* Fade-in animation for filtered items — NOT using .reveal to avoid IntersectionObserver dependency */
    .fade-in {
        animation: cardFadeIn 0.35s ease both;
    }

    @keyframes cardFadeIn {
        from {
            opacity: 0;
            transform: translateY(8px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    .project-card {
        text-decoration: none;
        border: 1px solid var(--border);
        border-radius: var(--radius-lg);
        overflow: hidden;
        transition: all var(--transition-base);
        background: var(--white);
    }

    .project-card:hover {
        border-color: var(--text-muted);
        transform: translateY(-2px);
        box-shadow: 0 8px 24px rgba(0, 0, 0, 0.06);
    }

    .project-image {
        position: relative;
        width: 100%;
        aspect-ratio: 16 / 10;
        overflow: hidden;
        background: var(--bg-alt);
    }

    .project-image img {
        width: 100%;
        height: 100%;
        object-fit: cover;
        transition: transform var(--transition-base);
    }

    .project-card:hover .project-image img {
        transform: scale(1.03);
    }

    .project-overlay {
        position: absolute;
        inset: 0;
        background: rgba(0, 0, 0, 0.5);
        display: flex;
        align-items: center;
        justify-content: center;
        opacity: 0;
        transition: opacity var(--transition-base);
    }

    .project-card:hover .project-overlay {
        opacity: 1;
    }

    .project-view {
        font-size: var(--text-sm);
        font-weight: 600;
        color: var(--white);
        padding: 10px 20px;
        border: 1px solid rgba(255, 255, 255, 0.6);
        border-radius: var(--radius-full);
    }

    .project-body {
        padding: var(--space-lg);
    }

    .project-meta-row {
        margin-bottom: var(--space-sm);
    }

    .project-cat {
        font-size: var(--text-xs);
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        color: var(--text-muted);
    }

    .project-title {
        font-size: var(--text-lg);
        font-weight: 700;
        color: var(--text);
        margin-bottom: var(--space-xs);
    }

    .project-desc {
        font-size: var(--text-sm);
        color: var(--text-secondary);
        line-height: 1.6;
        margin-bottom: var(--space-md);
        display: -webkit-box;
        -webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
        overflow: hidden;
    }

    .project-tags {
        display: flex;
        flex-wrap: wrap;
        gap: 4px;
    }

    .empty-state {
        text-align: center;
        padding: var(--space-4xl) 0;
        color: var(--text-muted);
    }

    @media (max-width: 768px) {
        .projects-grid {
            grid-template-columns: 1fr;
        }

        .filters {
            flex-wrap: wrap;
        }
    }
</style>
