// src/components/Footer.tsx
import { Github, Linkedin, Mail } from 'lucide-react';

export default function Footer() {
    return (
        <footer className="bg-black text-white py-12 border-t border-white/10">
            <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-6">
                <div>
                    <h2 className="text-xl font-bold font-display">Cahyadi Prasetyo.</h2>
                    <p className="text-gray-400 text-sm mt-2">
                        © {new Date().getFullYear()} All rights reserved.
                    </p>
                </div>

                <div className="flex gap-6">
                    <a href="#" className="p-2 bg-white/5 border border-white/10 rounded-full hover:bg-white hover:text-black transition-colors text-white">
                        <Github size={20} />
                    </a>
                    <a href="#" className="p-2 bg-white/5 border border-white/10 rounded-full hover:bg-white hover:text-black transition-colors text-white">
                        <Linkedin size={20} />
                    </a>
                    <a href="#" className="p-2 bg-white/5 border border-white/10 rounded-full hover:bg-white hover:text-black transition-colors text-white">
                        <Mail size={20} />
                    </a>
                </div>
            </div>
        </footer>
    );
}

// src/lib/components/Footer.svelte
<script lang="ts">
    import { getTranslations } from "$lib/i18n/index.svelte";
    const t = $derived(getTranslations());
</script>

<footer class="footer">
    <div class="container">
        <div class="footer-inner">
            <p class="footer-copy">{t.footer.copy}</p>
            <div class="footer-links">
                <a href="https://github.com/Cahyadi-Prasetyo" target="_blank" rel="noopener">GitHub</a>
                <a href="https://linkedin.com/" target="_blank" rel="noopener">LinkedIn</a>
                <a href="https://instagram.com/" target="_blank" rel="noopener">Instagram</a>
            </div>
        </div>
    </div>
</footer>

<style>
    .footer {
        padding: var(--space-xl) 0;
        border-top: 1px solid var(--border);
    }

    .footer-inner {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .footer-copy {
        font-size: var(--text-xs);
        color: var(--text-muted);
    }

    .footer-links {
        display: flex;
        gap: var(--space-lg);
    }

    .footer-links a {
        font-size: var(--text-xs);
        font-weight: 500;
        color: var(--text-muted);
        transition: color var(--transition-fast);
    }

    .footer-links a:hover {
        color: var(--text);
    }

    @media (max-width: 640px) {
        .footer-inner {
            flex-direction: column;
            gap: var(--space-md);
        }
    }
</style>
